# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ChickenFlaskApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://myflaskapp123.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7ec709cb7dfc4eeea7d4358b14fe4f81 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_60827c7b6b03414f827176a3bffd34d2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: myflaskapp123.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7ec709cb7dfc4eeea7d4358b14fe4f81 }}/chicken:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ChickenFlaskApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0ae061643f08438da06f7efa5bddc472 }}
        images: 'myflaskapp123.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7ec709cb7dfc4eeea7d4358b14fe4f81 }}/chicken:${{ github.sha }}'